name: Test Action Exercise

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This is the specific step you requested
      - name: 23f2003958@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      
